# Generated by Django 2.0 on 2023-07-08 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_in_cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
