# Generated by Django 2.0 on 2023-07-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_is_in_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, default='https://artsmidnorthcoast.com/wp-content/uploads/2014/05/no-image-available-icon-6.png'),
        ),
    ]
